<?php
const doctype = '<!doctype html>';
const html_open = '<html>';
const htm_close = '</html>';
const head_open = '<head>';
const head_close = '</head>';
const body_open = '<body>';
const body_close = '</body>';
const DIV_OPEN = '<div>';
const div_close = '</div>';
const div_main_open = '<div>';
const td_close = '<td>';
const td_close = '</td>';
const tr_open = '<tr>';
const tr_close = '</tr>';
const th_open = '<th>';
const th_open_30 = '<th colspan="30">';
const th_close = '</th>';
const H1_OPEN = '<h1>';
const H1_CLOSE = '</h1>';
const form_close = '</form>';
const table_open = '<table align="center">';
const table_close = '</table>';
const label_open = '<label>';
const lable_close = '</label>';
const SELECT_CLOSE = '</select>';
const FIELDset_OPEN = '<fieldset>';
const FIELDset_CLOSE = '</fieldset>';
const BLOCKQUOTE_OPEN = '<blockquote>';
const BLOCKQUOTE_CLOSE = '</blockquote>';
