<?php
const doctype = '<!doctype html>';
const open_html = '<html>';
const close_html = '</html>';
const open_head = '<head>';
const close_head = '</head>';
const open_body = '<body>';
const close_body = '</body>';
const open_div = '<div>';
const close_div = '</div>';
const open_td = '<td>';
const open_td_2 = '<td colspan="2" style="text-align: right; width: 30%">';
const open_td_3 = '<td colspan="2" style="text-align: center">';
const open_td_center = '<td style="text-align: center;">';
const close_td = '</td>';
const open_tr = '<tr>';
const close_tr = '</tr>';
const open_th = '<th>';
const open_th_2 = '<td colspan="2" style="text-align: right">';
const close_th = '</th>';
const open_h1 = '<h1 id="titulo">';
const close_h1 = '</h1>';
const open_h2 = '<h2>';
const close_h2 = '</h2>';
const close_form = '</form>';
const open_table = '<table align="center">';
const open_table_2 = '<table align="center" class="lista">';
const open_table_3 = '<table align="center" class="lista_3">';
const close_table = '</table>';
const open_label = '<label>';
const close_lable = '</label>';
const close_select = '</select>';
const open_blockquote = '<blockquote>';
const close_blockquote = '</blockquote>';